
/*

   test_tangle_regenerate_auto.c : This code is auto-generated by 'assemble_tangleregentest.py' and shouldn't be edited by hand. It contains tests for the orientation and interior code in pd_regenerate_tangle.


*/

#ifdef HAVE_CONFIG_H
  #include"config.h"
#endif

#include<stdio.h>
#include<assert.h>
#include<string.h>

#ifdef HAVE_STDINT_H
   #include<stdint.h>
#endif

#include<stdlib.h>

#ifdef HAVE_STDBOOL_H
   #include<stdbool.h>
#endif

#include<plcTopology.h>

#ifndef PD_VERBOSE /* We have switched to defining PD_VERBOSE as preprocessor symbol */
#define PD_VERBOSE 0
#endif


int main() {

  PD_VERBOSE = 50;

  printf("test_tangle_regenerate_auto (%s)\n",PACKAGE_STRING);
  printf("--------------------------------------------------------\n"
	 "Unit tests for pd_tangle_regenerate. \n"
	 "========================================================\n");

  if () {

    printf("=======================================================\n");
    printf("test_tangle_regenerate_auto:  PASS.\n");
    exit(0);

  } else {

    printf("=====================================================\n");
    printf("test_tangle_regenerate_auto:  FAIL.\n");
    exit(1);

  }

  return 0;

}