#!/bin/bash
if type -P libtoolize &> /dev/null; then
    echo "Calling libtoolize"
    libtoolize --force
else
  if type -P glibtoolize &> /dev/null; then
    glibtoolize --force
    echo "Calling glibtoolize"
  else 
    echo "Could not find libtoolize or glibtoolize. Please run one of them manually."
    exit
  fi
fi

rm -f config.cache
aclocal
autoconf
autoheader
automake -a
exit
