/* tangle interior test g assembled c code */

pd_code_t *pd_create_tangle_testg_0() { 

/* This procedure is machine generated by pd_write_c */
/* and probably shouldn't be hand-edited. */

pd_code_t *pd;
pd = pd_code_new(12);
assert(pd != NULL);
pd->ncross = 12;
pd->nedges = 24;
pd->ncomps = 3;
pd->nfaces = 14;
sprintf(pd->hash,"%s","DBgOBgUFBAQEBAMDAgICAgIDEAQEAAA");

/* Crossing data. */

pd->cross[0].edge[0] = 0;
pd->cross[0].edge[1] = 2;
pd->cross[0].edge[2] = 15;
pd->cross[0].edge[3] = 3;
pd->cross[0].sign = 1;

pd->cross[1].edge[0] = 0;
pd->cross[1].edge[1] = 5;
pd->cross[1].edge[2] = 1;
pd->cross[1].edge[3] = 6;
pd->cross[1].sign = 1;

pd->cross[2].edge[0] = 1;
pd->cross[2].edge[1] = 7;
pd->cross[2].edge[2] = 2;
pd->cross[2].edge[3] = 6;
pd->cross[2].sign = 1;

pd->cross[3].edge[0] = 3;
pd->cross[3].edge[1] = 10;
pd->cross[3].edge[2] = 4;
pd->cross[3].edge[3] = 11;
pd->cross[3].sign = 0;

pd->cross[4].edge[0] = 4;
pd->cross[4].edge[1] = 12;
pd->cross[4].edge[2] = 5;
pd->cross[4].edge[3] = 11;
pd->cross[4].sign = 0;

pd->cross[5].edge[0] = 7;
pd->cross[5].edge[1] = 14;
pd->cross[5].edge[2] = 8;
pd->cross[5].edge[3] = 15;
pd->cross[5].sign = 0;

pd->cross[6].edge[0] = 8;
pd->cross[6].edge[1] = 20;
pd->cross[6].edge[2] = 9;
pd->cross[6].edge[3] = 23;
pd->cross[6].sign = 1;

pd->cross[7].edge[0] = 9;
pd->cross[7].edge[1] = 22;
pd->cross[7].edge[2] = 10;
pd->cross[7].edge[3] = 23;
pd->cross[7].sign = 1;

pd->cross[8].edge[0] = 12;
pd->cross[8].edge[1] = 17;
pd->cross[8].edge[2] = 13;
pd->cross[8].edge[3] = 16;
pd->cross[8].sign = 0;

pd->cross[9].edge[0] = 13;
pd->cross[9].edge[1] = 19;
pd->cross[9].edge[2] = 14;
pd->cross[9].edge[3] = 16;
pd->cross[9].sign = 0;

pd->cross[10].edge[0] = 17;
pd->cross[10].edge[1] = 22;
pd->cross[10].edge[2] = 18;
pd->cross[10].edge[3] = 21;
pd->cross[10].sign = 0;

pd->cross[11].edge[0] = 18;
pd->cross[11].edge[1] = 20;
pd->cross[11].edge[2] = 19;
pd->cross[11].edge[3] = 21;
pd->cross[11].sign = 0;


/* Edge data */

pd->edge[0].head = 1;
pd->edge[0].headpos = 0;
pd->edge[0].tail = 0;
pd->edge[0].tailpos = 0;

pd->edge[1].head = 2;
pd->edge[1].headpos = 0;
pd->edge[1].tail = 1;
pd->edge[1].tailpos = 2;

pd->edge[2].head = 0;
pd->edge[2].headpos = 1;
pd->edge[2].tail = 2;
pd->edge[2].tailpos = 2;

pd->edge[3].head = 3;
pd->edge[3].headpos = 0;
pd->edge[3].tail = 0;
pd->edge[3].tailpos = 3;

pd->edge[4].head = 4;
pd->edge[4].headpos = 0;
pd->edge[4].tail = 3;
pd->edge[4].tailpos = 2;

pd->edge[5].head = 1;
pd->edge[5].headpos = 1;
pd->edge[5].tail = 4;
pd->edge[5].tailpos = 2;

pd->edge[6].head = 2;
pd->edge[6].headpos = 3;
pd->edge[6].tail = 1;
pd->edge[6].tailpos = 3;

pd->edge[7].head = 5;
pd->edge[7].headpos = 0;
pd->edge[7].tail = 2;
pd->edge[7].tailpos = 1;

pd->edge[8].head = 6;
pd->edge[8].headpos = 0;
pd->edge[8].tail = 5;
pd->edge[8].tailpos = 2;

pd->edge[9].head = 7;
pd->edge[9].headpos = 0;
pd->edge[9].tail = 6;
pd->edge[9].tailpos = 2;

pd->edge[10].head = 3;
pd->edge[10].headpos = 1;
pd->edge[10].tail = 7;
pd->edge[10].tailpos = 2;

pd->edge[11].head = 4;
pd->edge[11].headpos = 3;
pd->edge[11].tail = 3;
pd->edge[11].tailpos = 3;

pd->edge[12].head = 8;
pd->edge[12].headpos = 0;
pd->edge[12].tail = 4;
pd->edge[12].tailpos = 1;

pd->edge[13].head = 9;
pd->edge[13].headpos = 0;
pd->edge[13].tail = 8;
pd->edge[13].tailpos = 2;

pd->edge[14].head = 5;
pd->edge[14].headpos = 1;
pd->edge[14].tail = 9;
pd->edge[14].tailpos = 2;

pd->edge[15].head = 0;
pd->edge[15].headpos = 2;
pd->edge[15].tail = 5;
pd->edge[15].tailpos = 3;

pd->edge[16].head = 8;
pd->edge[16].headpos = 3;
pd->edge[16].tail = 9;
pd->edge[16].tailpos = 3;

pd->edge[17].head = 10;
pd->edge[17].headpos = 0;
pd->edge[17].tail = 8;
pd->edge[17].tailpos = 1;

pd->edge[18].head = 11;
pd->edge[18].headpos = 0;
pd->edge[18].tail = 10;
pd->edge[18].tailpos = 2;

pd->edge[19].head = 9;
pd->edge[19].headpos = 1;
pd->edge[19].tail = 11;
pd->edge[19].tailpos = 2;

pd->edge[20].head = 11;
pd->edge[20].headpos = 1;
pd->edge[20].tail = 6;
pd->edge[20].tailpos = 1;

pd->edge[21].head = 10;
pd->edge[21].headpos = 3;
pd->edge[21].tail = 11;
pd->edge[21].tailpos = 3;

pd->edge[22].head = 7;
pd->edge[22].headpos = 1;
pd->edge[22].tail = 10;
pd->edge[22].tailpos = 1;

pd->edge[23].head = 6;
pd->edge[23].headpos = 3;
pd->edge[23].tail = 7;
pd->edge[23].tailpos = 3;


/* Component Data */

pd->comp[0].nedges = 16;
pd->comp[0].tag = 'A';

pd->comp[0].edge = calloc(pd->comp[0].nedges,sizeof(pd_idx_t));
assert(pd->comp[0].edge != NULL);

pd->comp[0].edge[0] = 0;
pd->comp[0].edge[1] = 1;
pd->comp[0].edge[2] = 2;
pd->comp[0].edge[3] = 3;
pd->comp[0].edge[4] = 4;
pd->comp[0].edge[5] = 5;
pd->comp[0].edge[6] = 6;
pd->comp[0].edge[7] = 7;
pd->comp[0].edge[8] = 8;
pd->comp[0].edge[9] = 9;
pd->comp[0].edge[10] = 10;
pd->comp[0].edge[11] = 11;
pd->comp[0].edge[12] = 12;
pd->comp[0].edge[13] = 13;
pd->comp[0].edge[14] = 14;
pd->comp[0].edge[15] = 15;

pd->comp[1].nedges = 4;
pd->comp[1].tag = 'B';

pd->comp[1].edge = calloc(pd->comp[1].nedges,sizeof(pd_idx_t));
assert(pd->comp[1].edge != NULL);

pd->comp[1].edge[0] = 16;
pd->comp[1].edge[1] = 17;
pd->comp[1].edge[2] = 18;
pd->comp[1].edge[3] = 19;

pd->comp[2].nedges = 4;
pd->comp[2].tag = 'C';

pd->comp[2].edge = calloc(pd->comp[2].nedges,sizeof(pd_idx_t));
assert(pd->comp[2].edge != NULL);

pd->comp[2].edge[0] = 20;
pd->comp[2].edge[1] = 21;
pd->comp[2].edge[2] = 22;
pd->comp[2].edge[3] = 23;


/* Face data */

pd->face[0].nedges = 6;
pd->face[0].edge = calloc(pd->face[0].nedges,sizeof(pd_idx_t));
pd->face[0].or = calloc(pd->face[0].nedges,sizeof(pd_or_t));
assert(pd->face[0].edge != NULL);
assert(pd->face[0].or != NULL);

pd->face[0].edge[0] = 1;
pd->face[0].or[0] = 0;

pd->face[0].edge[1] = 5;
pd->face[0].or[1] = 0;

pd->face[0].edge[2] = 12;
pd->face[0].or[2] = 1;

pd->face[0].edge[3] = 16;
pd->face[0].or[3] = 0;

pd->face[0].edge[4] = 14;
pd->face[0].or[4] = 1;

pd->face[0].edge[5] = 7;
pd->face[0].or[5] = 0;

pd->face[1].nedges = 5;
pd->face[1].edge = calloc(pd->face[1].nedges,sizeof(pd_idx_t));
pd->face[1].or = calloc(pd->face[1].nedges,sizeof(pd_or_t));
assert(pd->face[1].edge != NULL);
assert(pd->face[1].or != NULL);

pd->face[1].edge[0] = 3;
pd->face[1].or[0] = 0;

pd->face[1].edge[1] = 15;
pd->face[1].or[1] = 0;

pd->face[1].edge[2] = 8;
pd->face[1].or[2] = 1;

pd->face[1].edge[3] = 23;
pd->face[1].or[3] = 0;

pd->face[1].edge[4] = 10;
pd->face[1].or[4] = 1;

pd->face[2].nedges = 5;
pd->face[2].edge = calloc(pd->face[2].nedges,sizeof(pd_idx_t));
pd->face[2].or = calloc(pd->face[2].nedges,sizeof(pd_or_t));
assert(pd->face[2].edge != NULL);
assert(pd->face[2].or != NULL);

pd->face[2].edge[0] = 4;
pd->face[2].or[0] = 0;

pd->face[2].edge[1] = 10;
pd->face[2].or[1] = 0;

pd->face[2].edge[2] = 22;
pd->face[2].or[2] = 0;

pd->face[2].edge[3] = 17;
pd->face[2].or[3] = 0;

pd->face[2].edge[4] = 12;
pd->face[2].or[4] = 0;

pd->face[3].nedges = 4;
pd->face[3].edge = calloc(pd->face[3].nedges,sizeof(pd_idx_t));
pd->face[3].or = calloc(pd->face[3].nedges,sizeof(pd_or_t));
assert(pd->face[3].edge != NULL);
assert(pd->face[3].or != NULL);

pd->face[3].edge[0] = 0;
pd->face[3].or[0] = 0;

pd->face[3].edge[1] = 3;
pd->face[3].or[1] = 1;

pd->face[3].edge[2] = 11;
pd->face[3].or[2] = 1;

pd->face[3].edge[3] = 5;
pd->face[3].or[3] = 1;

pd->face[4].nedges = 4;
pd->face[4].edge = calloc(pd->face[4].nedges,sizeof(pd_idx_t));
pd->face[4].or = calloc(pd->face[4].nedges,sizeof(pd_or_t));
assert(pd->face[4].edge != NULL);
assert(pd->face[4].or != NULL);

pd->face[4].edge[0] = 8;
pd->face[4].or[0] = 0;

pd->face[4].edge[1] = 14;
pd->face[4].or[1] = 0;

pd->face[4].edge[2] = 19;
pd->face[4].or[2] = 0;

pd->face[4].edge[3] = 20;
pd->face[4].or[3] = 0;

pd->face[5].nedges = 4;
pd->face[5].edge = calloc(pd->face[5].nedges,sizeof(pd_idx_t));
pd->face[5].or = calloc(pd->face[5].nedges,sizeof(pd_or_t));
assert(pd->face[5].edge != NULL);
assert(pd->face[5].or != NULL);

pd->face[5].edge[0] = 9;
pd->face[5].or[0] = 0;

pd->face[5].edge[1] = 20;
pd->face[5].or[1] = 1;

pd->face[5].edge[2] = 18;
pd->face[5].or[2] = 0;

pd->face[5].edge[3] = 22;
pd->face[5].or[3] = 1;

pd->face[6].nedges = 4;
pd->face[6].edge = calloc(pd->face[6].nedges,sizeof(pd_idx_t));
pd->face[6].or = calloc(pd->face[6].nedges,sizeof(pd_or_t));
assert(pd->face[6].edge != NULL);
assert(pd->face[6].or != NULL);

pd->face[6].edge[0] = 13;
pd->face[6].or[0] = 0;

pd->face[6].edge[1] = 17;
pd->face[6].or[1] = 1;

pd->face[6].edge[2] = 21;
pd->face[6].or[2] = 0;

pd->face[6].edge[3] = 19;
pd->face[6].or[3] = 1;

pd->face[7].nedges = 3;
pd->face[7].edge = calloc(pd->face[7].nedges,sizeof(pd_idx_t));
pd->face[7].or = calloc(pd->face[7].nedges,sizeof(pd_or_t));
assert(pd->face[7].edge != NULL);
assert(pd->face[7].or != NULL);

pd->face[7].edge[0] = 0;
pd->face[7].or[0] = 1;

pd->face[7].edge[1] = 6;
pd->face[7].or[1] = 1;

pd->face[7].edge[2] = 2;
pd->face[7].or[2] = 1;

pd->face[8].nedges = 3;
pd->face[8].edge = calloc(pd->face[8].nedges,sizeof(pd_idx_t));
pd->face[8].or = calloc(pd->face[8].nedges,sizeof(pd_or_t));
assert(pd->face[8].edge != NULL);
assert(pd->face[8].or != NULL);

pd->face[8].edge[0] = 2;
pd->face[8].or[0] = 0;

pd->face[8].edge[1] = 7;
pd->face[8].or[1] = 1;

pd->face[8].edge[2] = 15;
pd->face[8].or[2] = 1;

pd->face[9].nedges = 2;
pd->face[9].edge = calloc(pd->face[9].nedges,sizeof(pd_idx_t));
pd->face[9].or = calloc(pd->face[9].nedges,sizeof(pd_or_t));
assert(pd->face[9].edge != NULL);
assert(pd->face[9].or != NULL);

pd->face[9].edge[0] = 1;
pd->face[9].or[0] = 1;

pd->face[9].edge[1] = 6;
pd->face[9].or[1] = 0;

pd->face[10].nedges = 2;
pd->face[10].edge = calloc(pd->face[10].nedges,sizeof(pd_idx_t));
pd->face[10].or = calloc(pd->face[10].nedges,sizeof(pd_or_t));
assert(pd->face[10].edge != NULL);
assert(pd->face[10].or != NULL);

pd->face[10].edge[0] = 4;
pd->face[10].or[0] = 1;

pd->face[10].edge[1] = 11;
pd->face[10].or[1] = 0;

pd->face[11].nedges = 2;
pd->face[11].edge = calloc(pd->face[11].nedges,sizeof(pd_idx_t));
pd->face[11].or = calloc(pd->face[11].nedges,sizeof(pd_or_t));
assert(pd->face[11].edge != NULL);
assert(pd->face[11].or != NULL);

pd->face[11].edge[0] = 9;
pd->face[11].or[0] = 1;

pd->face[11].edge[1] = 23;
pd->face[11].or[1] = 1;

pd->face[12].nedges = 2;
pd->face[12].edge = calloc(pd->face[12].nedges,sizeof(pd_idx_t));
pd->face[12].or = calloc(pd->face[12].nedges,sizeof(pd_or_t));
assert(pd->face[12].edge != NULL);
assert(pd->face[12].or != NULL);

pd->face[12].edge[0] = 13;
pd->face[12].or[0] = 1;

pd->face[12].edge[1] = 16;
pd->face[12].or[1] = 1;

pd->face[13].nedges = 2;
pd->face[13].edge = calloc(pd->face[13].nedges,sizeof(pd_idx_t));
pd->face[13].or = calloc(pd->face[13].nedges,sizeof(pd_or_t));
assert(pd->face[13].edge != NULL);
assert(pd->face[13].or != NULL);

pd->face[13].edge[0] = 18;
pd->face[13].or[0] = 1;

pd->face[13].edge[1] = 21;
pd->face[13].or[1] = 1;


/* End of data. */

assert(pd_ok(pd));
return pd;

}


bool tangle_testg() {

  /*               +------------------------------------------------------+      */
/*               |           ____<16_________                           |      */
/*    (0)        |          /         (12)   \                          |      */
/*       _____12>__________________13>_______ \ ___14>_                 |      */
/*      /        |          8                  \9      \                |      */
/*     /         |         |       (6)         |        \               |      */
/*     |         |         17                 19         \              |      */
/*   _____       |         \  _____<21__ ____  |    (4)   \             |      */
/*  /   4 \      |  (2)     v/               \ /          |             |      */
/* /   |   ^     |        10 \         (13)   \ 11        |             |      */
/* |   |    4    |          / \              / \          |             |      */
/* |   |     \   |         /   \___18>______/   ^         |             |      */
/* 5   \(10) |   |        22                    20        |             |      */
/* v    ^    |   |        |      (5)            |         |             |<-T   */
/* |     \11_______<10___ | _________<9_______________<8_ | __________  |      */
/* |          3  |        \7                     6        |5          \ |      */
/* |         |   |         \        (11)        |         |           | |      */
/* |  (3)    |   |          \                   /         |           | |      */
/* |         ^   |           \___23>___________/          15          | |      */
/* |         3   |                                        v           | |      */
/* |         |   +----------------------------------------/-----------|-+      */
/* |         |                                   (1)     /            |        */
/* \    _<0_ | _________________________________________/             /        */
/*  \  /     2 0                                                     /         */
/*    /  (7) |                   (8)                                /          */
/*   /\_6>_________________7>______________________________________/           */
/*  / 1       2                                                                */
/*  |        |                                                                 */
/*  |   (9)  |                                                                 */
/*  |        /                                                                 */
/*  \___1>__/                                                                  */
pd_idx_t nedges = 4 ;
pd_idx_t tangle_faces[4] = {0,2,1,8} ;
pd_idx_t tangle_edges[4] = {12,10,15,7} ;
pd_boundary_or_t edge_bdy_or[4] = {in,out,out,in} ;

pd_idx_t ninterior_cross = 7 ;
pd_idx_t interior_cross[7] = {5,6,7,8,9,10,11} ;

pd_idx_t ninterior_edges = 12 ;
pd_idx_t interior_edge[12] = {8,9,13,14,16,17,18,19,20,21,22,23} ;


  printf("---------------------------------------\n"
	 "tangle_regenerate test g\n"
	 "---------------------------------------\n");

  printf("creating pd...");
  pd_code_t *pd = pd_create_tangle_testg_0();
  if (!pd_ok(pd)) {

    printf("fail (doesn't pass pd_ok)\n");
    return false;

  }
  
  printf("pass (passes pd_ok)\n");

  printf("creating basic tangle information...");
  pd_tangle_t *t = pd_tangle_new(nedges);

  pd_idx_t i;
  for(i=0;i<t->nedges;i++) {
  
    t->edge[i] = tangle_edges[i];
    t->face[i] = tangle_faces[i];

  }

  printf("done (tangle has %d edges)\n",nedges);

  printf("running pd_regenerate_tangle...");
  pd_regenerate_tangle(pd,t);

  if (!pd_tangle_ok(pd,t)) {

    printf("fail (doesn't pass pd_tangle_ok)\n");
    return false;
    
  }

  printf("pass (didn't crash, passes pd_tangle_ok)\n");

  printf("testing edge boundary orientations...");

  for(i=0;i<t->nedges;i++) {

    if (t->edge_bdy_or[i] != edge_bdy_or[i]) {

      pd_idx_t j;

      printf("fail (list of boundary orientations for tangles doesn't match expected at pos %d)\n",i);

      printf("found:   ");

      for(j=0;j<t->nedges;j++) {

        if (t->edge_bdy_or[j] == in) { printf("  in "); }
        else { printf(" out "); }

      }

      printf("\n");

      printf("expected:");

      for(j=0;j<t->nedges;j++) {

        if (edge_bdy_or[j] == in) { printf("  in "); }
        else { printf(" out "); }

      }

      printf("\n");

      return false;

    }

  }

  printf("pass (edge boundary orientations match expected)\n");

  printf("checking interior crossings...");
  qsort(interior_cross,(size_t)(ninterior_cross),sizeof(pd_idx_t),pd_idx_cmp);

  if (t->ninterior_cross != ninterior_cross) {

    printf("fail (# interior crossings found (%d) != # expected (%d))\n",
    t->ninterior_cross,ninterior_cross);
    return false;

  }

  for(i=0;i<t->ninterior_cross;i++) {

     if (t->interior_cross[i] != interior_cross[i]) {

        pd_idx_t j;

        printf("fail (list of interior crossings doesn't match expected at pos %d)\n",i);

        printf("found:   ");

        for(j=0;j<t->ninterior_cross;j++) {

          printf(" %4d ",t->interior_cross[j]);

        }

        printf("\n");

        printf("expected:");

        for(j=0;j<t->ninterior_cross;j++) {

          printf(" %4d ",interior_cross[j]);

        }

        printf("\n");

        return false;

    }

  }

  printf("pass (interior crossings match)\n");


  printf("checking interior edges...");
  qsort(interior_edge,(size_t)(ninterior_edges),sizeof(pd_idx_t),pd_idx_cmp);

  if (t->ninterior_edges != ninterior_edges) {

    printf("fail (# interior edges found (%d) != # expected (%d))\n",
    t->ninterior_edges,ninterior_edges);
    return false;

  }

  for(i=0;i<t->ninterior_edges;i++) {

     if (t->interior_edge[i] != interior_edge[i]) {

        pd_idx_t j;

        printf("fail (list of interior edges doesn't match expected at pos %d)\n",i);

        printf("found:    ");

        for(j=0;j<t->ninterior_edges;j++) {

          printf(" %4d ",t->interior_edge[j]);

        }

        printf("\n");

        printf("expected:");

        for(j=0;j<t->ninterior_edges;j++) {

          printf(" %4d ",interior_edge[j]);

        }

        printf("\n");

        return false;

    }

  }

  printf("pass (interior edges match)\n");
  
  printf("housecleaning...");
  
  pd_code_free(&pd);
  pd_tangle_free(&t);

  printf("done\n");

  printf("---------------------------------------\n"
         "tangle test g : PASS\n"
	     "---------------------------------------\n");
  
  return true;

}