pd_code_t *pd_create_tangle_testk_0() { 

/* This procedure is machine generated by pd_write_c */
/* and probably shouldn't be hand-edited. */

pd_code_t *pd;
pd = pd_code_new(28);
assert(pd != NULL);
pd->ncross = 28;
pd->nedges = 56;
pd->ncomps = 3;
pd->nfaces = 30;
sprintf(pd->hash,"%s","HDgeDwcGBAQEBAQEBAQEBAQDAwMDAwM");

/* Crossing data. */

pd->cross[0].edge[0] = 0;
pd->cross[0].edge[1] = 35;
pd->cross[0].edge[2] = 33;
pd->cross[0].edge[3] = 34;
pd->cross[0].sign = 0;

pd->cross[1].edge[0] = 0;
pd->cross[1].edge[1] = 36;
pd->cross[1].edge[2] = 1;
pd->cross[1].edge[3] = 35;
pd->cross[1].sign = 0;

pd->cross[2].edge[0] = 1;
pd->cross[2].edge[1] = 32;
pd->cross[2].edge[2] = 2;
pd->cross[2].edge[3] = 33;
pd->cross[2].sign = 0;

pd->cross[3].edge[0] = 2;
pd->cross[3].edge[1] = 55;
pd->cross[3].edge[2] = 3;
pd->cross[3].edge[3] = 48;
pd->cross[3].sign = 1;

pd->cross[4].edge[0] = 3;
pd->cross[4].edge[1] = 51;
pd->cross[4].edge[2] = 4;
pd->cross[4].edge[3] = 50;
pd->cross[4].sign = 1;

pd->cross[5].edge[0] = 4;
pd->cross[5].edge[1] = 8;
pd->cross[5].edge[2] = 5;
pd->cross[5].edge[3] = 7;
pd->cross[5].sign = 0;

pd->cross[6].edge[0] = 5;
pd->cross[6].edge[1] = 44;
pd->cross[6].edge[2] = 6;
pd->cross[6].edge[3] = 45;
pd->cross[6].sign = 0;

pd->cross[7].edge[0] = 6;
pd->cross[7].edge[1] = 46;
pd->cross[7].edge[2] = 7;
pd->cross[7].edge[3] = 45;
pd->cross[7].sign = 0;

pd->cross[8].edge[0] = 8;
pd->cross[8].edge[1] = 12;
pd->cross[8].edge[2] = 9;
pd->cross[8].edge[3] = 11;
pd->cross[8].sign = 0;

pd->cross[9].edge[0] = 9;
pd->cross[9].edge[1] = 42;
pd->cross[9].edge[2] = 10;
pd->cross[9].edge[3] = 43;
pd->cross[9].sign = 0;

pd->cross[10].edge[0] = 10;
pd->cross[10].edge[1] = 44;
pd->cross[10].edge[2] = 11;
pd->cross[10].edge[3] = 43;
pd->cross[10].sign = 0;

pd->cross[11].edge[0] = 12;
pd->cross[11].edge[1] = 51;
pd->cross[11].edge[2] = 13;
pd->cross[11].edge[3] = 52;
pd->cross[11].sign = 1;

pd->cross[12].edge[0] = 13;
pd->cross[12].edge[1] = 55;
pd->cross[12].edge[2] = 14;
pd->cross[12].edge[3] = 54;
pd->cross[12].sign = 1;

pd->cross[13].edge[0] = 14;
pd->cross[13].edge[1] = 32;
pd->cross[13].edge[2] = 15;
pd->cross[13].edge[3] = 31;
pd->cross[13].sign = 0;

pd->cross[14].edge[0] = 15;
pd->cross[14].edge[1] = 38;
pd->cross[14].edge[2] = 16;
pd->cross[14].edge[3] = 39;
pd->cross[14].sign = 0;

pd->cross[15].edge[0] = 16;
pd->cross[15].edge[1] = 29;
pd->cross[15].edge[2] = 17;
pd->cross[15].edge[3] = 30;
pd->cross[15].sign = 1;

pd->cross[16].edge[0] = 17;
pd->cross[16].edge[1] = 24;
pd->cross[16].edge[2] = 18;
pd->cross[16].edge[3] = 25;
pd->cross[16].sign = 1;

pd->cross[17].edge[0] = 18;
pd->cross[17].edge[1] = 21;
pd->cross[17].edge[2] = 19;
pd->cross[17].edge[3] = 22;
pd->cross[17].sign = 1;

pd->cross[18].edge[0] = 19;
pd->cross[18].edge[1] = 23;
pd->cross[18].edge[2] = 20;
pd->cross[18].edge[3] = 22;
pd->cross[18].sign = 0;

pd->cross[19].edge[0] = 20;
pd->cross[19].edge[1] = 23;
pd->cross[19].edge[2] = 21;
pd->cross[19].edge[3] = 24;
pd->cross[19].sign = 1;

pd->cross[20].edge[0] = 25;
pd->cross[20].edge[1] = 29;
pd->cross[20].edge[2] = 26;
pd->cross[20].edge[3] = 28;
pd->cross[20].sign = 0;

pd->cross[21].edge[0] = 26;
pd->cross[21].edge[1] = 38;
pd->cross[21].edge[2] = 27;
pd->cross[21].edge[3] = 37;
pd->cross[21].sign = 0;

pd->cross[22].edge[0] = 27;
pd->cross[22].edge[1] = 36;
pd->cross[22].edge[2] = 28;
pd->cross[22].edge[3] = 37;
pd->cross[22].sign = 0;

pd->cross[23].edge[0] = 30;
pd->cross[23].edge[1] = 40;
pd->cross[23].edge[2] = 31;
pd->cross[23].edge[3] = 39;
pd->cross[23].sign = 0;

pd->cross[24].edge[0] = 34;
pd->cross[24].edge[1] = 48;
pd->cross[24].edge[2] = 47;
pd->cross[24].edge[3] = 49;
pd->cross[24].sign = 1;

pd->cross[25].edge[0] = 40;
pd->cross[25].edge[1] = 53;
pd->cross[25].edge[2] = 41;
pd->cross[25].edge[3] = 54;
pd->cross[25].sign = 1;

pd->cross[26].edge[0] = 41;
pd->cross[26].edge[1] = 53;
pd->cross[26].edge[2] = 42;
pd->cross[26].edge[3] = 52;
pd->cross[26].sign = 1;

pd->cross[27].edge[0] = 46;
pd->cross[27].edge[1] = 49;
pd->cross[27].edge[2] = 47;
pd->cross[27].edge[3] = 50;
pd->cross[27].sign = 1;


/* Edge data */

pd->edge[0].head = 1;
pd->edge[0].headpos = 0;
pd->edge[0].tail = 0;
pd->edge[0].tailpos = 0;

pd->edge[1].head = 2;
pd->edge[1].headpos = 0;
pd->edge[1].tail = 1;
pd->edge[1].tailpos = 2;

pd->edge[2].head = 3;
pd->edge[2].headpos = 0;
pd->edge[2].tail = 2;
pd->edge[2].tailpos = 2;

pd->edge[3].head = 4;
pd->edge[3].headpos = 0;
pd->edge[3].tail = 3;
pd->edge[3].tailpos = 2;

pd->edge[4].head = 5;
pd->edge[4].headpos = 0;
pd->edge[4].tail = 4;
pd->edge[4].tailpos = 2;

pd->edge[5].head = 6;
pd->edge[5].headpos = 0;
pd->edge[5].tail = 5;
pd->edge[5].tailpos = 2;

pd->edge[6].head = 7;
pd->edge[6].headpos = 0;
pd->edge[6].tail = 6;
pd->edge[6].tailpos = 2;

pd->edge[7].head = 5;
pd->edge[7].headpos = 3;
pd->edge[7].tail = 7;
pd->edge[7].tailpos = 2;

pd->edge[8].head = 8;
pd->edge[8].headpos = 0;
pd->edge[8].tail = 5;
pd->edge[8].tailpos = 1;

pd->edge[9].head = 9;
pd->edge[9].headpos = 0;
pd->edge[9].tail = 8;
pd->edge[9].tailpos = 2;

pd->edge[10].head = 10;
pd->edge[10].headpos = 0;
pd->edge[10].tail = 9;
pd->edge[10].tailpos = 2;

pd->edge[11].head = 8;
pd->edge[11].headpos = 3;
pd->edge[11].tail = 10;
pd->edge[11].tailpos = 2;

pd->edge[12].head = 11;
pd->edge[12].headpos = 0;
pd->edge[12].tail = 8;
pd->edge[12].tailpos = 1;

pd->edge[13].head = 12;
pd->edge[13].headpos = 0;
pd->edge[13].tail = 11;
pd->edge[13].tailpos = 2;

pd->edge[14].head = 13;
pd->edge[14].headpos = 0;
pd->edge[14].tail = 12;
pd->edge[14].tailpos = 2;

pd->edge[15].head = 14;
pd->edge[15].headpos = 0;
pd->edge[15].tail = 13;
pd->edge[15].tailpos = 2;

pd->edge[16].head = 15;
pd->edge[16].headpos = 0;
pd->edge[16].tail = 14;
pd->edge[16].tailpos = 2;

pd->edge[17].head = 16;
pd->edge[17].headpos = 0;
pd->edge[17].tail = 15;
pd->edge[17].tailpos = 2;

pd->edge[18].head = 17;
pd->edge[18].headpos = 0;
pd->edge[18].tail = 16;
pd->edge[18].tailpos = 2;

pd->edge[19].head = 18;
pd->edge[19].headpos = 0;
pd->edge[19].tail = 17;
pd->edge[19].tailpos = 2;

pd->edge[20].head = 19;
pd->edge[20].headpos = 0;
pd->edge[20].tail = 18;
pd->edge[20].tailpos = 2;

pd->edge[21].head = 17;
pd->edge[21].headpos = 1;
pd->edge[21].tail = 19;
pd->edge[21].tailpos = 2;

pd->edge[22].head = 18;
pd->edge[22].headpos = 3;
pd->edge[22].tail = 17;
pd->edge[22].tailpos = 3;

pd->edge[23].head = 19;
pd->edge[23].headpos = 1;
pd->edge[23].tail = 18;
pd->edge[23].tailpos = 1;

pd->edge[24].head = 16;
pd->edge[24].headpos = 1;
pd->edge[24].tail = 19;
pd->edge[24].tailpos = 3;

pd->edge[25].head = 20;
pd->edge[25].headpos = 0;
pd->edge[25].tail = 16;
pd->edge[25].tailpos = 3;

pd->edge[26].head = 21;
pd->edge[26].headpos = 0;
pd->edge[26].tail = 20;
pd->edge[26].tailpos = 2;

pd->edge[27].head = 22;
pd->edge[27].headpos = 0;
pd->edge[27].tail = 21;
pd->edge[27].tailpos = 2;

pd->edge[28].head = 20;
pd->edge[28].headpos = 3;
pd->edge[28].tail = 22;
pd->edge[28].tailpos = 2;

pd->edge[29].head = 15;
pd->edge[29].headpos = 1;
pd->edge[29].tail = 20;
pd->edge[29].tailpos = 1;

pd->edge[30].head = 23;
pd->edge[30].headpos = 0;
pd->edge[30].tail = 15;
pd->edge[30].tailpos = 3;

pd->edge[31].head = 13;
pd->edge[31].headpos = 3;
pd->edge[31].tail = 23;
pd->edge[31].tailpos = 2;

pd->edge[32].head = 2;
pd->edge[32].headpos = 1;
pd->edge[32].tail = 13;
pd->edge[32].tailpos = 1;

pd->edge[33].head = 0;
pd->edge[33].headpos = 2;
pd->edge[33].tail = 2;
pd->edge[33].tailpos = 3;

pd->edge[34].head = 0;
pd->edge[34].headpos = 3;
pd->edge[34].tail = 24;
pd->edge[34].tailpos = 0;

pd->edge[35].head = 1;
pd->edge[35].headpos = 3;
pd->edge[35].tail = 0;
pd->edge[35].tailpos = 1;

pd->edge[36].head = 22;
pd->edge[36].headpos = 1;
pd->edge[36].tail = 1;
pd->edge[36].tailpos = 1;

pd->edge[37].head = 21;
pd->edge[37].headpos = 3;
pd->edge[37].tail = 22;
pd->edge[37].tailpos = 3;

pd->edge[38].head = 14;
pd->edge[38].headpos = 1;
pd->edge[38].tail = 21;
pd->edge[38].tailpos = 1;

pd->edge[39].head = 23;
pd->edge[39].headpos = 3;
pd->edge[39].tail = 14;
pd->edge[39].tailpos = 3;

pd->edge[40].head = 25;
pd->edge[40].headpos = 0;
pd->edge[40].tail = 23;
pd->edge[40].tailpos = 1;

pd->edge[41].head = 26;
pd->edge[41].headpos = 0;
pd->edge[41].tail = 25;
pd->edge[41].tailpos = 2;

pd->edge[42].head = 9;
pd->edge[42].headpos = 1;
pd->edge[42].tail = 26;
pd->edge[42].tailpos = 2;

pd->edge[43].head = 10;
pd->edge[43].headpos = 3;
pd->edge[43].tail = 9;
pd->edge[43].tailpos = 3;

pd->edge[44].head = 6;
pd->edge[44].headpos = 1;
pd->edge[44].tail = 10;
pd->edge[44].tailpos = 1;

pd->edge[45].head = 7;
pd->edge[45].headpos = 3;
pd->edge[45].tail = 6;
pd->edge[45].tailpos = 3;

pd->edge[46].head = 27;
pd->edge[46].headpos = 0;
pd->edge[46].tail = 7;
pd->edge[46].tailpos = 1;

pd->edge[47].head = 24;
pd->edge[47].headpos = 2;
pd->edge[47].tail = 27;
pd->edge[47].tailpos = 2;

pd->edge[48].head = 24;
pd->edge[48].headpos = 1;
pd->edge[48].tail = 3;
pd->edge[48].tailpos = 3;

pd->edge[49].head = 27;
pd->edge[49].headpos = 1;
pd->edge[49].tail = 24;
pd->edge[49].tailpos = 3;

pd->edge[50].head = 4;
pd->edge[50].headpos = 3;
pd->edge[50].tail = 27;
pd->edge[50].tailpos = 3;

pd->edge[51].head = 11;
pd->edge[51].headpos = 1;
pd->edge[51].tail = 4;
pd->edge[51].tailpos = 1;

pd->edge[52].head = 26;
pd->edge[52].headpos = 3;
pd->edge[52].tail = 11;
pd->edge[52].tailpos = 3;

pd->edge[53].head = 25;
pd->edge[53].headpos = 1;
pd->edge[53].tail = 26;
pd->edge[53].tailpos = 1;

pd->edge[54].head = 12;
pd->edge[54].headpos = 3;
pd->edge[54].tail = 25;
pd->edge[54].tailpos = 3;

pd->edge[55].head = 3;
pd->edge[55].headpos = 1;
pd->edge[55].tail = 12;
pd->edge[55].tailpos = 1;


/* Component Data */

pd->comp[0].nedges = 34;
pd->comp[0].tag = 'A';

pd->comp[0].edge = calloc(pd->comp[0].nedges,sizeof(pd_idx_t));
assert(pd->comp[0].edge != NULL);

pd->comp[0].edge[0] = 0;
pd->comp[0].edge[1] = 1;
pd->comp[0].edge[2] = 2;
pd->comp[0].edge[3] = 3;
pd->comp[0].edge[4] = 4;
pd->comp[0].edge[5] = 5;
pd->comp[0].edge[6] = 6;
pd->comp[0].edge[7] = 7;
pd->comp[0].edge[8] = 8;
pd->comp[0].edge[9] = 9;
pd->comp[0].edge[10] = 10;
pd->comp[0].edge[11] = 11;
pd->comp[0].edge[12] = 12;
pd->comp[0].edge[13] = 13;
pd->comp[0].edge[14] = 14;
pd->comp[0].edge[15] = 15;
pd->comp[0].edge[16] = 16;
pd->comp[0].edge[17] = 17;
pd->comp[0].edge[18] = 18;
pd->comp[0].edge[19] = 19;
pd->comp[0].edge[20] = 20;
pd->comp[0].edge[21] = 21;
pd->comp[0].edge[22] = 22;
pd->comp[0].edge[23] = 23;
pd->comp[0].edge[24] = 24;
pd->comp[0].edge[25] = 25;
pd->comp[0].edge[26] = 26;
pd->comp[0].edge[27] = 27;
pd->comp[0].edge[28] = 28;
pd->comp[0].edge[29] = 29;
pd->comp[0].edge[30] = 30;
pd->comp[0].edge[31] = 31;
pd->comp[0].edge[32] = 32;
pd->comp[0].edge[33] = 33;

pd->comp[1].nedges = 14;
pd->comp[1].tag = 'B';

pd->comp[1].edge = calloc(pd->comp[1].nedges,sizeof(pd_idx_t));
assert(pd->comp[1].edge != NULL);

pd->comp[1].edge[0] = 34;
pd->comp[1].edge[1] = 35;
pd->comp[1].edge[2] = 36;
pd->comp[1].edge[3] = 37;
pd->comp[1].edge[4] = 38;
pd->comp[1].edge[5] = 39;
pd->comp[1].edge[6] = 40;
pd->comp[1].edge[7] = 41;
pd->comp[1].edge[8] = 42;
pd->comp[1].edge[9] = 43;
pd->comp[1].edge[10] = 44;
pd->comp[1].edge[11] = 45;
pd->comp[1].edge[12] = 46;
pd->comp[1].edge[13] = 47;

pd->comp[2].nedges = 8;
pd->comp[2].tag = 'C';

pd->comp[2].edge = calloc(pd->comp[2].nedges,sizeof(pd_idx_t));
assert(pd->comp[2].edge != NULL);

pd->comp[2].edge[0] = 48;
pd->comp[2].edge[1] = 49;
pd->comp[2].edge[2] = 50;
pd->comp[2].edge[3] = 51;
pd->comp[2].edge[4] = 52;
pd->comp[2].edge[5] = 53;
pd->comp[2].edge[6] = 54;
pd->comp[2].edge[7] = 55;


/* Face data */

pd->face[0].nedges = 15;
pd->face[0].edge = calloc(pd->face[0].nedges,sizeof(pd_idx_t));
pd->face[0].or = calloc(pd->face[0].nedges,sizeof(pd_or_t));
assert(pd->face[0].edge != NULL);
assert(pd->face[0].or != NULL);

pd->face[0].edge[0] = 0;
pd->face[0].or[0] = 0;

pd->face[0].edge[1] = 34;
pd->face[0].or[1] = 0;

pd->face[0].edge[2] = 49;
pd->face[0].or[2] = 1;

pd->face[0].edge[3] = 46;
pd->face[0].or[3] = 0;

pd->face[0].edge[4] = 6;
pd->face[0].or[4] = 0;

pd->face[0].edge[5] = 44;
pd->face[0].or[5] = 0;

pd->face[0].edge[6] = 10;
pd->face[0].or[6] = 0;

pd->face[0].edge[7] = 42;
pd->face[0].or[7] = 0;

pd->face[0].edge[8] = 53;
pd->face[0].or[8] = 1;

pd->face[0].edge[9] = 40;
pd->face[0].or[9] = 0;

pd->face[0].edge[10] = 30;
pd->face[0].or[10] = 0;

pd->face[0].edge[11] = 17;
pd->face[0].or[11] = 1;

pd->face[0].edge[12] = 25;
pd->face[0].or[12] = 1;

pd->face[0].edge[13] = 28;
pd->face[0].or[13] = 0;

pd->face[0].edge[14] = 36;
pd->face[0].or[14] = 0;

pd->face[1].nedges = 7;
pd->face[1].edge = calloc(pd->face[1].nedges,sizeof(pd_idx_t));
pd->face[1].or = calloc(pd->face[1].nedges,sizeof(pd_or_t));
assert(pd->face[1].edge != NULL);
assert(pd->face[1].or != NULL);

pd->face[1].edge[0] = 17;
pd->face[1].or[0] = 0;

pd->face[1].edge[1] = 29;
pd->face[1].or[1] = 0;

pd->face[1].edge[2] = 25;
pd->face[1].or[2] = 0;

pd->face[1].edge[3] = 18;
pd->face[1].or[3] = 1;

pd->face[1].edge[4] = 22;
pd->face[1].or[4] = 1;

pd->face[1].edge[5] = 20;
pd->face[1].or[5] = 1;

pd->face[1].edge[6] = 24;
pd->face[1].or[6] = 1;

pd->face[2].nedges = 6;
pd->face[2].edge = calloc(pd->face[2].nedges,sizeof(pd_idx_t));
pd->face[2].or = calloc(pd->face[2].nedges,sizeof(pd_or_t));
assert(pd->face[2].edge != NULL);
assert(pd->face[2].or != NULL);

pd->face[2].edge[0] = 1;
pd->face[2].or[0] = 0;

pd->face[2].edge[1] = 36;
pd->face[2].or[1] = 1;

pd->face[2].edge[2] = 27;
pd->face[2].or[2] = 0;

pd->face[2].edge[3] = 38;
pd->face[2].or[3] = 1;

pd->face[2].edge[4] = 15;
pd->face[2].or[4] = 0;

pd->face[2].edge[5] = 32;
pd->face[2].or[5] = 1;

pd->face[3].nedges = 4;
pd->face[3].edge = calloc(pd->face[3].nedges,sizeof(pd_idx_t));
pd->face[3].or = calloc(pd->face[3].nedges,sizeof(pd_or_t));
assert(pd->face[3].edge != NULL);
assert(pd->face[3].or != NULL);

pd->face[3].edge[0] = 2;
pd->face[3].or[0] = 0;

pd->face[3].edge[1] = 32;
pd->face[3].or[1] = 0;

pd->face[3].edge[2] = 14;
pd->face[3].or[2] = 0;

pd->face[3].edge[3] = 55;
pd->face[3].or[3] = 1;

pd->face[4].nedges = 4;
pd->face[4].edge = calloc(pd->face[4].nedges,sizeof(pd_idx_t));
pd->face[4].or = calloc(pd->face[4].nedges,sizeof(pd_or_t));
assert(pd->face[4].edge != NULL);
assert(pd->face[4].or != NULL);

pd->face[4].edge[0] = 2;
pd->face[4].or[0] = 1;

pd->face[4].edge[1] = 48;
pd->face[4].or[1] = 1;

pd->face[4].edge[2] = 34;
pd->face[4].or[2] = 1;

pd->face[4].edge[3] = 33;
pd->face[4].or[3] = 0;

pd->face[5].nedges = 4;
pd->face[5].edge = calloc(pd->face[5].nedges,sizeof(pd_idx_t));
pd->face[5].or = calloc(pd->face[5].nedges,sizeof(pd_or_t));
assert(pd->face[5].edge != NULL);
assert(pd->face[5].or != NULL);

pd->face[5].edge[0] = 3;
pd->face[5].or[0] = 1;

pd->face[5].edge[1] = 50;
pd->face[5].or[1] = 0;

pd->face[5].edge[2] = 47;
pd->face[5].or[2] = 1;

pd->face[5].edge[3] = 48;
pd->face[5].or[3] = 0;

pd->face[6].nedges = 4;
pd->face[6].edge = calloc(pd->face[6].nedges,sizeof(pd_idx_t));
pd->face[6].or = calloc(pd->face[6].nedges,sizeof(pd_or_t));
assert(pd->face[6].edge != NULL);
assert(pd->face[6].or != NULL);

pd->face[6].edge[0] = 3;
pd->face[6].or[0] = 0;

pd->face[6].edge[1] = 55;
pd->face[6].or[1] = 0;

pd->face[6].edge[2] = 13;
pd->face[6].or[2] = 0;

pd->face[6].edge[3] = 51;
pd->face[6].or[3] = 0;

pd->face[7].nedges = 4;
pd->face[7].edge = calloc(pd->face[7].nedges,sizeof(pd_idx_t));
pd->face[7].or = calloc(pd->face[7].nedges,sizeof(pd_or_t));
assert(pd->face[7].edge != NULL);
assert(pd->face[7].or != NULL);

pd->face[7].edge[0] = 4;
pd->face[7].or[0] = 1;

pd->face[7].edge[1] = 7;
pd->face[7].or[1] = 0;

pd->face[7].edge[2] = 46;
pd->face[7].or[2] = 1;

pd->face[7].edge[3] = 50;
pd->face[7].or[3] = 1;

pd->face[8].nedges = 4;
pd->face[8].edge = calloc(pd->face[8].nedges,sizeof(pd_idx_t));
pd->face[8].or = calloc(pd->face[8].nedges,sizeof(pd_or_t));
assert(pd->face[8].edge != NULL);
assert(pd->face[8].or != NULL);

pd->face[8].edge[0] = 4;
pd->face[8].or[0] = 0;

pd->face[8].edge[1] = 51;
pd->face[8].or[1] = 1;

pd->face[8].edge[2] = 12;
pd->face[8].or[2] = 0;

pd->face[8].edge[3] = 8;
pd->face[8].or[3] = 0;

pd->face[9].nedges = 4;
pd->face[9].edge = calloc(pd->face[9].nedges,sizeof(pd_idx_t));
pd->face[9].or = calloc(pd->face[9].nedges,sizeof(pd_or_t));
assert(pd->face[9].edge != NULL);
assert(pd->face[9].or != NULL);

pd->face[9].edge[0] = 5;
pd->face[9].or[0] = 0;

pd->face[9].edge[1] = 8;
pd->face[9].or[1] = 1;

pd->face[9].edge[2] = 11;
pd->face[9].or[2] = 0;

pd->face[9].edge[3] = 44;
pd->face[9].or[3] = 1;

pd->face[10].nedges = 4;
pd->face[10].edge = calloc(pd->face[10].nedges,sizeof(pd_idx_t));
pd->face[10].or = calloc(pd->face[10].nedges,sizeof(pd_or_t));
assert(pd->face[10].edge != NULL);
assert(pd->face[10].or != NULL);

pd->face[10].edge[0] = 9;
pd->face[10].or[0] = 0;

pd->face[10].edge[1] = 12;
pd->face[10].or[1] = 1;

pd->face[10].edge[2] = 52;
pd->face[10].or[2] = 1;

pd->face[10].edge[3] = 42;
pd->face[10].or[3] = 1;

pd->face[11].nedges = 4;
pd->face[11].edge = calloc(pd->face[11].nedges,sizeof(pd_idx_t));
pd->face[11].or = calloc(pd->face[11].nedges,sizeof(pd_or_t));
assert(pd->face[11].edge != NULL);
assert(pd->face[11].or != NULL);

pd->face[11].edge[0] = 13;
pd->face[11].or[0] = 1;

pd->face[11].edge[1] = 54;
pd->face[11].or[1] = 0;

pd->face[11].edge[2] = 41;
pd->face[11].or[2] = 1;

pd->face[11].edge[3] = 52;
pd->face[11].or[3] = 0;

pd->face[12].nedges = 4;
pd->face[12].edge = calloc(pd->face[12].nedges,sizeof(pd_idx_t));
pd->face[12].or = calloc(pd->face[12].nedges,sizeof(pd_or_t));
assert(pd->face[12].edge != NULL);
assert(pd->face[12].or != NULL);

pd->face[12].edge[0] = 14;
pd->face[12].or[0] = 1;

pd->face[12].edge[1] = 31;
pd->face[12].or[1] = 0;

pd->face[12].edge[2] = 40;
pd->face[12].or[2] = 1;

pd->face[12].edge[3] = 54;
pd->face[12].or[3] = 1;

pd->face[13].nedges = 4;
pd->face[13].edge = calloc(pd->face[13].nedges,sizeof(pd_idx_t));
pd->face[13].or = calloc(pd->face[13].nedges,sizeof(pd_or_t));
assert(pd->face[13].edge != NULL);
assert(pd->face[13].or != NULL);

pd->face[13].edge[0] = 16;
pd->face[13].or[0] = 0;

pd->face[13].edge[1] = 38;
pd->face[13].or[1] = 0;

pd->face[13].edge[2] = 26;
pd->face[13].or[2] = 0;

pd->face[13].edge[3] = 29;
pd->face[13].or[3] = 1;

pd->face[14].nedges = 3;
pd->face[14].edge = calloc(pd->face[14].nedges,sizeof(pd_idx_t));
pd->face[14].or = calloc(pd->face[14].nedges,sizeof(pd_or_t));
assert(pd->face[14].edge != NULL);
assert(pd->face[14].or != NULL);

pd->face[14].edge[0] = 1;
pd->face[14].or[0] = 1;

pd->face[14].edge[1] = 33;
pd->face[14].or[1] = 1;

pd->face[14].edge[2] = 35;
pd->face[14].or[2] = 1;

pd->face[15].nedges = 3;
pd->face[15].edge = calloc(pd->face[15].nedges,sizeof(pd_idx_t));
pd->face[15].or = calloc(pd->face[15].nedges,sizeof(pd_or_t));
assert(pd->face[15].edge != NULL);
assert(pd->face[15].or != NULL);

pd->face[15].edge[0] = 5;
pd->face[15].or[0] = 1;

pd->face[15].edge[1] = 45;
pd->face[15].or[1] = 1;

pd->face[15].edge[2] = 7;
pd->face[15].or[2] = 1;

pd->face[16].nedges = 3;
pd->face[16].edge = calloc(pd->face[16].nedges,sizeof(pd_idx_t));
pd->face[16].or = calloc(pd->face[16].nedges,sizeof(pd_or_t));
assert(pd->face[16].edge != NULL);
assert(pd->face[16].or != NULL);

pd->face[16].edge[0] = 9;
pd->face[16].or[0] = 1;

pd->face[16].edge[1] = 43;
pd->face[16].or[1] = 1;

pd->face[16].edge[2] = 11;
pd->face[16].or[2] = 1;

pd->face[17].nedges = 3;
pd->face[17].edge = calloc(pd->face[17].nedges,sizeof(pd_idx_t));
pd->face[17].or = calloc(pd->face[17].nedges,sizeof(pd_or_t));
assert(pd->face[17].edge != NULL);
assert(pd->face[17].or != NULL);

pd->face[17].edge[0] = 15;
pd->face[17].or[0] = 1;

pd->face[17].edge[1] = 39;
pd->face[17].or[1] = 1;

pd->face[17].edge[2] = 31;
pd->face[17].or[2] = 1;

pd->face[18].nedges = 3;
pd->face[18].edge = calloc(pd->face[18].nedges,sizeof(pd_idx_t));
pd->face[18].or = calloc(pd->face[18].nedges,sizeof(pd_or_t));
assert(pd->face[18].edge != NULL);
assert(pd->face[18].or != NULL);

pd->face[18].edge[0] = 16;
pd->face[18].or[0] = 1;

pd->face[18].edge[1] = 30;
pd->face[18].or[1] = 1;

pd->face[18].edge[2] = 39;
pd->face[18].or[2] = 0;

pd->face[19].nedges = 3;
pd->face[19].edge = calloc(pd->face[19].nedges,sizeof(pd_idx_t));
pd->face[19].or = calloc(pd->face[19].nedges,sizeof(pd_or_t));
assert(pd->face[19].edge != NULL);
assert(pd->face[19].or != NULL);

pd->face[19].edge[0] = 18;
pd->face[19].or[0] = 0;

pd->face[19].edge[1] = 24;
pd->face[19].or[1] = 0;

pd->face[19].edge[2] = 21;
pd->face[19].or[2] = 1;

pd->face[20].nedges = 3;
pd->face[20].edge = calloc(pd->face[20].nedges,sizeof(pd_idx_t));
pd->face[20].or = calloc(pd->face[20].nedges,sizeof(pd_or_t));
assert(pd->face[20].edge != NULL);
assert(pd->face[20].or != NULL);

pd->face[20].edge[0] = 19;
pd->face[20].or[0] = 0;

pd->face[20].edge[1] = 21;
pd->face[20].or[1] = 0;

pd->face[20].edge[2] = 23;
pd->face[20].or[2] = 0;

pd->face[21].nedges = 3;
pd->face[21].edge = calloc(pd->face[21].nedges,sizeof(pd_idx_t));
pd->face[21].or = calloc(pd->face[21].nedges,sizeof(pd_or_t));
assert(pd->face[21].edge != NULL);
assert(pd->face[21].or != NULL);

pd->face[21].edge[0] = 26;
pd->face[21].or[0] = 1;

pd->face[21].edge[1] = 37;
pd->face[21].or[1] = 0;

pd->face[21].edge[2] = 28;
pd->face[21].or[2] = 1;

pd->face[22].nedges = 2;
pd->face[22].edge = calloc(pd->face[22].nedges,sizeof(pd_idx_t));
pd->face[22].or = calloc(pd->face[22].nedges,sizeof(pd_or_t));
assert(pd->face[22].edge != NULL);
assert(pd->face[22].or != NULL);

pd->face[22].edge[0] = 0;
pd->face[22].or[0] = 1;

pd->face[22].edge[1] = 35;
pd->face[22].or[1] = 0;

pd->face[23].nedges = 2;
pd->face[23].edge = calloc(pd->face[23].nedges,sizeof(pd_idx_t));
pd->face[23].or = calloc(pd->face[23].nedges,sizeof(pd_or_t));
assert(pd->face[23].edge != NULL);
assert(pd->face[23].or != NULL);

pd->face[23].edge[0] = 6;
pd->face[23].or[0] = 1;

pd->face[23].edge[1] = 45;
pd->face[23].or[1] = 0;

pd->face[24].nedges = 2;
pd->face[24].edge = calloc(pd->face[24].nedges,sizeof(pd_idx_t));
pd->face[24].or = calloc(pd->face[24].nedges,sizeof(pd_or_t));
assert(pd->face[24].edge != NULL);
assert(pd->face[24].or != NULL);

pd->face[24].edge[0] = 10;
pd->face[24].or[0] = 1;

pd->face[24].edge[1] = 43;
pd->face[24].or[1] = 0;

pd->face[25].nedges = 2;
pd->face[25].edge = calloc(pd->face[25].nedges,sizeof(pd_idx_t));
pd->face[25].or = calloc(pd->face[25].nedges,sizeof(pd_or_t));
assert(pd->face[25].edge != NULL);
assert(pd->face[25].or != NULL);

pd->face[25].edge[0] = 19;
pd->face[25].or[0] = 1;

pd->face[25].edge[1] = 22;
pd->face[25].or[1] = 0;

pd->face[26].nedges = 2;
pd->face[26].edge = calloc(pd->face[26].nedges,sizeof(pd_idx_t));
pd->face[26].or = calloc(pd->face[26].nedges,sizeof(pd_or_t));
assert(pd->face[26].edge != NULL);
assert(pd->face[26].or != NULL);

pd->face[26].edge[0] = 20;
pd->face[26].or[0] = 0;

pd->face[26].edge[1] = 23;
pd->face[26].or[1] = 1;

pd->face[27].nedges = 2;
pd->face[27].edge = calloc(pd->face[27].nedges,sizeof(pd_idx_t));
pd->face[27].or = calloc(pd->face[27].nedges,sizeof(pd_or_t));
assert(pd->face[27].edge != NULL);
assert(pd->face[27].or != NULL);

pd->face[27].edge[0] = 27;
pd->face[27].or[0] = 1;

pd->face[27].edge[1] = 37;
pd->face[27].or[1] = 1;

pd->face[28].nedges = 2;
pd->face[28].edge = calloc(pd->face[28].nedges,sizeof(pd_idx_t));
pd->face[28].or = calloc(pd->face[28].nedges,sizeof(pd_or_t));
assert(pd->face[28].edge != NULL);
assert(pd->face[28].or != NULL);

pd->face[28].edge[0] = 41;
pd->face[28].or[0] = 0;

pd->face[28].edge[1] = 53;
pd->face[28].or[1] = 0;

pd->face[29].nedges = 2;
pd->face[29].edge = calloc(pd->face[29].nedges,sizeof(pd_idx_t));
pd->face[29].or = calloc(pd->face[29].nedges,sizeof(pd_or_t));
assert(pd->face[29].edge != NULL);
assert(pd->face[29].or != NULL);

pd->face[29].edge[0] = 47;
pd->face[29].or[0] = 0;

pd->face[29].edge[1] = 49;
pd->face[29].or[1] = 0;


/* End of data. */

assert(pd_ok(pd));
return pd;

}

