#!perl
#
#
# Fill the knotvects directory with files copied from TightKnot/vects in
# order to compute a table of HOMFLY polynomials for plc_knottype.
#

use warnings;
use Lingua::EN::Numbers qw(num2en num2en_ordinal);
use File::Slurp;
use Data::Dumper;
use File::Copy;

sub make_safekey {

    my $key = $_[0];
    my $safekey;
    my $texkey;

    my $cr;
    my $ind;
    my $comp;

    my $safeone;
    my $safetwo;
    my $safethree;
    
    if ( $key !~ /.vect/ ) {  #this is a knot type
	
	if ( $key =~ /(\d+)_(\d+)_(\d+)/ ) { # a link
	    
	    $safeone = $1; $safetwo = $2; $safethree = $3;

	    $cr = num2en($safeone); $comp = num2en($safetwo); $ind = num2en($safethree);
	    $cr =~ s/\s/\-/g; $comp =~ s/\s/\-/g; $ind =~ s/\s/\-/g;
	   
	    $cr =~ s/\b(\w)(\w*)/uc($1).lc($2)/ge;
	    $comp =~ s/\b(\w)(\w*)/uc($1).lc($2)/ge;
	    $ind =~ s/\b(\w)(\w*)/uc($1).lc($2)/ge;
	    
	    $safekey = $cr.$comp.$ind;
	    $safekey =~ s/-//g;
	    $texkey = $safeone."^{".$safetwo."}_{".$safethree."}";

	    $cr = $safeone; $comp = $safetwo; $ind = $safethree;
	    
	} elsif ( $key =~ /(\d+)_(\d+)/ ) { # a knot
	
	    $safeone = $1; 
	    $safetwo = $2;
	    
	    $texkey = $safeone."_{".$safetwo."}";
    
	    $cr = num2en($safeone); $ind = num2en($safetwo);
	    $cr =~ s/\s/\-/g; $ind =~ s/\s/\-/g;

	    $cr =~ s/\b(\w)(\w*)/uc($1).lc($2)/ge;
	    $ind =~ s/\b(\w)(\w*)/uc($1).lc($2)/ge;
	    

	    $safekey = $cr.$ind;
	    $safekey =~ s/-//g;
	
	    $cr = $safeone; $comp = 1; $ind = $safetwo;

	} else {

	    print "FAILED to match key ".$key."\n";

	}


    }
	
    my @retstuff = ($safekey,$texkey,$cr,$comp,$ind);

    return @retstuff;
	    
}

#open(DB,'KnotDB.pl');
my $DBFILE = read_file('../../TightKnot/KnotDB.pl');
my %knots;

eval($DBFILE);

#close(DB);

my $numkeys = keys ( %knots );
print "We have $numkeys entries in the original database. Looking for knots.\n";

# first, a pass to remove files from the hash

my $key;

foreach $key ( sort(keys %knots) ) {

    if ($key =~ /.vect/) {

	delete $knots{$key};

    }

}

$numkeys = keys ( %knots );
print "There seem to be $numkeys knots and links in the database...\n";


# now a pass through the knotchart-prime.txt file.
my @rawtable;

open(TABLE,"knotchart-prime.txt") || die("Couldn't open knotchart...\n");
@rawtable = <TABLE>;
close(TABLE);

my $knotline;
my $knot;
my $tag;
my $symtype;
my $mod;
my $operation;
my $newfile;
my $fname;
my @ktab;
my $homfly;

foreach $knotline ( @rawtable ) {

    my $knotrec = { };

    chomp($knotline);
    ($knot,$symtype) = split(/ /,$knotline);

    print("$knot -> ");

    # We now need to split the "m", "r", or "rm" from the knot type

    if ($knot =~ m/(\d+_\d+)(m|rm|r)/) {
	
	$tag = $1; $mod = $2;
	if ($mod =~ m/rm/) {

	  $operation = '"(-1,-1,e)"';

	} elsif ($mod =~ m/m/) {

	  $operation = '"(-1,1,e)"';

	} elsif ($mod =~ m/r/) {

	  $operation = '"(1,-1,e)"';

	}

    } else {

	$tag = $knot; $mod = 'e';
	$operation = '"(1,1,e)"';

    }

    print("$tag and $mod -> $operation");

    # Now we need to create the appropriate file and move it into the vect
    # directory.

    $fname = $knots{$tag}{filename};

    copy("/Users/cantarel/TightKnot/vects/".$fname,"./knotvects/".$tag.".vect") or die("Can't copy file $fname from TightKnot/vects/ to ./knotvects/$tag.vect");

    chdir("./knotvects");

    open(WHITTENVECT,"whittenvect ".'2>/dev/null'." -o $operation $tag.vect |");
    while (<WHITTENVECT>) {
      if (/Wrote modified VECT file to:\s*(\S+)\n/) { 
	    $newfile = $1;
	  } else {
	    $newfile = "Could not detect filename";
	  } 
    }
    close WHITTENVECT;

    chdir("..");

    print(" -> $newfile");

    # Now we need to actually generate the header file with the data by running the homfly code. 

    open(KNOTTYPE,"knottype -qh /Users/cantarel/plCurve/data/knotvects/$newfile |");
    while (<KNOTTYPE>) {

      if (/Homfly polynomial:\((.+)\)/) {
	$homfly = $1;
      } else {
	print
      }
    }

    print(" -> $homfly\n");
	   
    $knotrec->{homfly} = $homfly;
    $knotrec->{sym}    = $operation;

    $tag =~ /(\d+)_(\d+)/;
    $knotrec->{cr} = $1;
    $knotrec->{ind} = $2;
    $knotrec->{filename} = $newfile;

    push(@ktab,$knotrec);

  }


print "Completed processing knotchart.\n";

# Now we sort the table by homfly

my @knotlist = sort{ $a->{homfly} cmp $b->{homfly} } @ktab ;
my $ntypes;

$ntypes = scalar @ktab;
$ntypes++;

print "Generated table of $ntypes homfly polynomials for different knot types. Writing header file...\n";

# We generate the homfly database file

open(HOMFLY,">/Users/cantarel/plCurve/homfly.h") || die("Could not open homfly.h header file.\n");

print HOMFLY <<ENDC;

/* 
    homfly.h : This file contains a small data structure designed to store the homfly
    polynomials of knots and links to 10 crossings. This file is automatically generated
    by /data/fillKnotVects.pl and should not be edited by hand. We are filling in values
    of data type plc_knottype, which is defined in plCurve.h.

    #define MAXPRIMEFACTORS 10
    #define MAXHOMFLY       1024

    struct knottypestruct {

      int  nf;                            // Number of prime factors 
      int  cr[MAXPRIMEFACTORS];           // Crossing number of each prime factor 
      int  ind[MAXPRIMEFACTORS];          // Index (in Rolfsen or Cerf) of each prime factor 
      char sym[MAXPRIMEFACTORS][128];     // Symmetry tag (Whitten group element) for each prime factor 
      char homfly[MAXHOMFLY];             // Homfly polynomial (as plc_lmpoly output) 

    } plc_knottype;

*/

ENDC

print HOMFLY "#define KTDBSIZE ".($ntypes-1)."\n";

print HOMFLY "plc_knottype ktdb[$ntypes]  = { \\\n";

my %tag;

foreach $tag ( @knotlist ) {

  print HOMFLY "{ 1, { $tag->{cr} }, { $tag->{ind} }, { $tag->{sym} }, \"$tag->{homfly}\" }, \\\n";

}

print HOMFLY " { 1, { 0 }, { 1 }, { \"(1,1,e)\"}, {\"[0]\"} } \\\n";  # add a guy to take care of trailing comma
print HOMFLY "};\n";

close(HOMFLY);
