/* plc_xoshiro.h.  Generated by configure.  */
/*
 *
 * Data structures and prototypes for the random number generator xoshiro. 
 *
 *  $Id: plCurve.h,v 1.57 2007-07-12 15:27:52 cantarel Exp $
 *
 */

/* Copyright 2004 The University of Georgia */

/* This file is part of plCurve. */

/*@-exportlocal@*/
#ifndef PLCURVE_XOSHIRO_H
#define PLCURVE_XOSHIRO_H

#if (__cplusplus || c_plusplus)
extern "C" {
#endif
  
uint64_t *plc_xoshiro_init(uint64_t init);
void plc_xoshiro_free(uint64_t *rng);
double plc_xoshiro_uniform(uint64_t *state);
  
#if (__cplusplus || c_plusplus)
};
#endif
#endif /* PLCXOSHIRO_H */
/*@=exportlocal@*/
